# =============================================================================
# zOS Greeter — Hyprland config for login screen
# =============================================================================

monitor = , preferred, auto, 1

source = /usr/share/zos/hypr/nvidia.conf

env = XCURSOR_SIZE,24
env = XCURSOR_THEME,catppuccin-mocha-dark-cursors
env = HYPRCURSOR_THEME,catppuccin-mocha-dark-cursors
env = HYPRCURSOR_SIZE,24

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

exec-once = hyprpaper -c /etc/greetd/hyprpaper.conf
exec-once = regreet; hyprctl dispatch exit

windowrulev2 = fullscreen, class:^(com.github.rharish101.ReGreet)$
