#!/bin/bash
# Show SDDM login on first connected monitor, others show background only

FIRST=""
for output in $(xrandr --query | grep " connected" | awk '{print $1}'); do
    if [ -z "$FIRST" ]; then
        FIRST="$output"
        xrandr --output "$output" --auto --primary
    else
        xrandr --output "$output" --auto --right-of "$FIRST"
    fi
done
